import os
import re

WORKING_DIR = os.environ.get("WORKING_DIR", os.path.join(os.path.dirname(__file__), "./working_dir"))
if not os.path.exists(WORKING_DIR):
    os.makedirs(WORKING_DIR)

BASE62_REGEX = re.compile(r"^[0-9a-zA-Z]+$")
SHA256_REGEX = re.compile(r"^[a-fA-F0-9]{64}$")
GENERIC_HASH_REGEX = re.compile(r"^([a-f0-9]{32}|[a-f0-9]{40}|[a-f0-9]{64})$")
DATE_FORMATS = [
    "%Y-%m",
    "%Y.%m",
    "%Y/%m",
    "%m/%d/%Y",
    "%d/%m/%Y",
    "%m/%d/%y",
    "%d/%m/%y",
    "%Y/%m/%d",
    "%y/%m/%d",
    "%Y/%d/%m",
    "%y/%d/%m",
    "%Y.%m.%d",
    "%y.%m.%d",
    "%Y.%d.%m",
    "%y.%d.%m",
    "%Y%m%d",
    "%y%m%d",
    "%Y%d%m",
    "%y%d%m",
    "%d-%m-%Y",
    "%m-%d-%Y",
    "%m-%d-%y",
    "%Y-%m-%d",
    "%d.%m.%Y",
    "%m.%d.%Y",
    "%m.%d.%y",
    "%Y.%m.%d",
    "%f/%e/%Y",
    "%f/%e/%y",
    "%e/%f/%Y",
    "%e/%f/%y",
    "%f-%e-%Y",
    "%f-%e-%y",
    "%e-%f-%Y",
    "%e-%f-%y",
    "%f.%e.%Y",
    "%f.%e.%y",
    "%e.%f.%Y",
    "%e.%f.%y",
    "%b %e, %Y",
    "%B %e, %Y",
    "%b %d, %Y",
    "%B %d, %Y",
    "%b %e %Y",
    "%B %e %Y",
    "%e %b %Y",
    "%e %B %Y",
    "%b %d %Y",
    "%B %d %Y",
    "%d %b %Y",
    "%d %B %Y",
    "%Y-%m-%d %I:%M:%S %p",
    "%Y/%m/%d %I:%M:%S %p%Y-%m-%d %H:%M:%S",
    "%Y/%m/%d %H:%M:%S",
    "%d-%b-%y",
    "%d-%b-%Y",
]

CATEGORY_KEYWORDS = {
    "MALWARE": ["MALWARE", "IMPLANT", "MALICIOUS", "MAL"],
    "EXPLOIT": ["EXPLOIT", "EXPLOITATION", "EXPL"],
    "TECHNIQUE": ["TECHNIQUE", "TTP", "TACTIC"],
    "TOOL": ["TOOL", "UTILITY", "SOFTWARE", "PENTEST", "TOOLS"],
    "INFO": ["INFO", "GEN", "GENERIC"],
    "VULNERABILITY": ["VULNERABILITY", "VULN", "WEAKNESS", "VULNDRIVER"],
}

ACTOR_TYPE_KEYWORDS = {
    "APT": ["APT", "ADVANCED PERSISTENT THREAT", "NATION STATE", "NATION-STATE", "STATE-SPONSORED"],
    "CRIMEWARE": ["CRIMEWARE", "CYBERCRIME", "CYBER-CRIME", "THEFT"],
    "FIN": ["FIN", "FINANCIAL-GAIN", "FINANCIAL", "FINANCIALLY"],
}

# Mapping of malware types to possible keywords found in YARA rule metadata
MALWARE_TYPE_KEYWORDS = {
    # Each malware type maps to a list of keywords/phrases that may be found in YARA rule metadata
    "ADWARE": ["ADWARE"],
    "BACKDOOR": ["BACKDOOR", "REMOTE ACCESS", "BKDR"],
    "BANKER": ["BANKER", "BANKING TROJAN"],
    "BOOTKIT": ["BOOTKIT", "BOOT RECORD"],
    "BOT": ["BOT", "BOTNET"],
    "BROWSER-HIJACKER": ["BROWSER-HIJACKER", "BROWSER HIJACKER"],
    "BRUTEFORCER": ["BRUTEFORCER", "BRUTE FORCER"],
    "CLICKFRAUD": ["CLICKFRAUD", "CLICK FRAUD"],
    "CRYPTOMINER": ["CRYPTOMINER", "CRYPTO MINER", "MINER"],
    "DDOS": ["DDOS", "DISTRIBUTED DENIAL OF SERVICE"],
    "DOWNLOADER": ["DOWNLOADER", "LNK", ".LNK"],
    "DROPPER": ["DROPPER"],
    "EXPLOITKIT": ["EXPLOITKIT", "EXPLOIT KIT"],
    "FAKEAV": ["FAKEAV", "FAKE AV", "FAKE ANTIVIRUS"],
    "HACKTOOL": ["HACKTOOL", "HACKING TOOL", "AVKILLER", "HKTL", "HACKTOOLS"],
    "INFOSTEALER": ["INFOSTEALER", "INFO STEALER", "INFORMATION STEALER", "STEALER"],
    "LOADER": ["LOADER", "STAGER", "INJECTOR", "INJECTION", "LOADING"],
    "KEYLOGGER": ["KEYLOGGER", "KEY LOGGER"],
    "OBFUSCATOR": ["OBFUSCATOR", "OBFUSCATION", "CRYPTER", "CRYPTOR"],
    "POS": ["POS", "POINT OF SALE", "POINT-OF-SALE"],
    "PROXY": ["PROXY"],
    "RAT": ["RAT", "REMOTE ACCESS TROJAN"],
    "RANSOMWARE": ["RANSOMWARE"],
    "REVERSE-PROXY": ["REVERSE-PROXY", "REVERSE PROXY"],
    "ROOTKIT": ["ROOTKIT"],
    "SCANNER": ["SCANNER"],
    "SCAREWARE": ["SCAREWARE"],
    "SPAMMER": ["SPAMMER"],
    "TROJAN": ["TROJAN", "TROJAN HORSE", "AVKILLER", "TROY"],
    "VIRUS": ["VIRUS"],
    "WIPER": ["WIPER"],
    "WEBSHELL": ["WEBSHELL", "WEB SHELL", "REVERSESHELL", "WEBSHELLS"],
    "WORM": ["WORM"],
}
