name: tests

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: run_test
    strategy:
      matrix:
        Python3_11:
          python.version: "3.11"
        Python3_12:
          python.version: "3.12"
        Python3_13:
          python.version: "3.13"

    timeoutInMinutes: 10

    steps:
      - task: UsePythonVersion@0
        displayName: Set python version
        inputs:
          versionSpec: "$(python.version)"
      - script: |
          sudo env "PATH=$PATH" python -m pip install -e .[test]
          sudo rm -rf /tmp/* /var/lib/apt/lists/* ~/.cache/pip

        displayName: Setup environment
      - script: |
          export REPO_NAME=${BUILD_REPOSITORY_NAME##*/}
          python -m pytest -p no:cacheprovider --durations=10 -rsx -vv
        displayName: Test
